name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

   
    steps:
    - uses: actions/checkout@v3
    - name: Fetch latest changes from remote repository
      run: git fetch --all && git reset --hard origin/main
    - name: git stash 
      working-directory: /home/ubuntu/soccerspot-mvp
      run: git stash

    - name: git pull 
      working-directory: /home/ubuntu/soccerspot-mvp
      run: git pull

    - name: npm i in frontend
      working-directory: /home/ubuntu/soccerspot-mvp/client
      run: npm i

    - name: npm i in backend
      working-directory: /home/ubuntu/soccerspot-mvp
      run: npm i
      
    - name: run build front end
      working-directory: /home/ubuntu/soccerspot-mvp/client
      run: npm run build

    - name: pm2 restart server
      working-directory: /home/ubuntu/soccerspot-mvp
      run: pm2 restart index.js --force